### ISSUE TITLE
Trouble processing URLs with international/encoded characters

### ISSUE THREAD

**Issue by demetriusnunes** [niiknow/docker-nginx-image-proxy#10]
Trying to process this url breaks:
https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Humait%C3%A1_-_Suvaco_do_Cristo_Redentor.jpg/800px-Humait%C3%A1_-_Suvaco_do_Cristo_Redentor.jpg

It's actually kind of weird passing the plain URL to the module as it's much safer and a best practice to encode URLs with `window.encodeURIComponent` or with base64 `window.btoa` functions.

Could we at least make this configurable?

**Comment by noogen** [comment]
Tip, look at x-imageproxy-debug in your browser network tab.

I output x-image-proxy debug which, as you have expected, URL is escaped by nginx as:  https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Humait%25C3%25A1_-_Suvaco_do_Cristo_Redentor.jpg/800px-Humait%25C3%25A1_-_Suvaco_do_Cristo_Redentor.jpg?w=200&h=-&q=96&r=0&e=0&cmd=resize&ofmt=

Of course, this would result in a 404: https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Humait%25C3%25A1_-_Suvaco_do_Cristo_Redentor.jpg/800px-Humait%25C3%25A1_-_Suvaco_do_Cristo_Redentor.jpg

nginx provide way to fix this:
```
set_unescape_uri $clean_uri $image_uri;
proxy_pass $clean_uri$is_args$args;
```

Just update your proxy_pass statements at:
https://github.com/niiknow/docker-nginx-image-proxy/blob/master/files/etc/nginx/sites-enabled/server.conf#L227
https://github.com/niiknow/docker-nginx-image-proxy/blob/master/files/etc/nginx/sites-enabled/server.conf#L248

**Comment by demetriusnunes** [comment]
Thanks, I'll try that!

**Comment by demetriusnunes** [comment]
Unfortunately, `set_unescape_uri` is not included in the current Docker image. Anyway you could include it?

**Comment by noogen** [comment]
Sorry, used it too much in openresty that I thought it was part of nginx.  I'm working on the build now.

**Comment by noogen** [comment]
Should work now: http://imageproxy.niiknow.org/rx/200/https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Humait%C3%A1_-_Suvaco_do_Cristo_Redentor.jpg/800px-Humait%C3%A1_-_Suvaco_do_Cristo_Redentor.jpg

**Comment by demetriusnunes** [comment]
Thanks!!!!

**Comment by demetriusnunes** [comment]
Although, I'm still having trouble if I use `encodeURIComponent` to encode URLs that have querystring parameters.

**Comment by noogen** [comment]
The new conf should unescape everything now.  Try again.

**Comment by demetriusnunes** [comment]
If I use `encodedURIComponent` to encode the URL with a querystring, I get a 500 error, like this:

http://imageproxy.niiknow.org/rx/350x300/http%3A%2F%2Fimages.ingaiasites.com.br%2FdmtBYQdKfjyypH9Ho5VU1mbsJDoxJt5Y.jpg%3Fcb%3D123

```
X-ImageProxy-Code:500
X-ImageProxy-Debug:http://images.ingaiasites.com.br/dmtBYQdKfjyypH9Ho5VU1mbsJDoxJt5Y.jpg%253Fcb=123?w=350&h=300&q=96&r=0&e=0&cmd=resize&ofmt=
```

**Comment by noogen** [comment]
I would suggest not to encode it, it's part of the URL path and not a query string.   The code work as expected because it's part of the path.  encodeURIComponent emphasis on Component is for query string.

**Comment by demetriusnunes** [comment]
Ok, thanks, I'm ok with it.
