### ISSUE TITLE
Is there a way to use a local image instead of an URL?

### ISSUE THREAD

**Issue by andreapernici** [niiknow/docker-nginx-image-proxy#14]
I really like this configuration, but I'd like to know if it works also with local image path instead of URL.

It could be upgraded also adding watermark filter.

**Comment by noogen** [comment]
Local image shouldn't be too hard, nginx image_filter module was designed to work with local image.  Mount  your docker volume **/usr/share/nginx/html** to a local folder and add your images folder and files.  Then you have two options:

1.  keep existing config and proxy your image with **http://localhost/images/your-image-path** like so **http://imageresize.domain.com/rx/transformation-instruction/http://localhost/images/your-image-path**
2.  or replace line 230 and 250 proxypass directive (https://github.com/niiknow/docker-nginx-image-proxy/blob/master/files/etc/nginx/sites-enabled/server.conf#L230)  with:
```
root /usr/share/nginx/html;
try_files "/images/$image_path" @empty;
```

===
As for watermark, this would be an enhancement pull-request.   I'm currently busy (on my long Vacation) and won't be available until middle of January 2018.  If you need it right away, you are always welcome to apply the patch from here **https://github.com/vdvm/nginx-watermark** and do a pull-request.

**Comment by noogen** [comment]
I added watermark function to image_filter module in v1.8.0 if you want to test it.   

Usage:
```
image_filter watermark /path/to/watermark.png [ bottom-right (default) | top-left | top-right | bottom-left | center ];
```

Based on the usage above, I'm not sure how I'm going to do the watermark from a nginx conf standpoint yet.  Here is the way Cloudinary does it:  https://cloudinary.com/cookbook/adding_watermarks_as_an_overlay

Maybe l_watermark_filepath and lp_watermark_position?

**Comment by noogen** [comment]
Any suggestion?  I'm thinking, you have a watermark image in nginx root path name "watermark.png"; then, you must pass wm_{position} where position is bottomright, topleft, center, etc...

You can override the default watermark by providing the watermark file path with wmpath_filename (must be png file) and must exists in the root folder.

**Comment by andreapernici** [comment]
Sorry noogen, for some reason I never received notification emails :(

Looking this only now. I think that setting the root pathname should work well.

**Comment by andreapernici** [comment]
I tested the watermark, but I'm not able to see it on the image.

**Comment by noogen** [comment]
What's your configuration look like?  Did you get any error?

Right now, the watermark implementation require an absolute path to file and it has to be PNG.  It will throw either, file not found or file is not a png: https://github.com/niiknow/docker-nginx-image-proxy/blob/master/build/src/ngx_http_image_filter_module.c#L1197

https://github.com/niiknow/docker-nginx-image-proxy/blob/master/build/src/ngx_http_image_filter_module.c#L1231
https://github.com/niiknow/docker-nginx-image-proxy/blob/master/build/src/ngx_http_image_filter_module.c#L1235

**Comment by andreapernici** [comment]
I put it in the /cmd/resize and /cmd/crop locations


image_filter watermark /mylogo.png;

the file it under the root path.

/var/root/mylogo.png and I can see it via browser.

**Comment by noogen** [comment]
try the full path to the file: "/var/root/mylogo.png"

**Comment by andreapernici** [comment]
It doesn't work the same. Maybe there are some limitation in the logo watermark size?

**Comment by andreapernici** [comment]
I'm using this
```
    location /cmd/resize {
        internal;

        proxy_pass                  $clean_uri;
        include                     /usr/local/nginx/conf/conf.d/proxy-hide-headers.common;

        add_header                  X-ImageProxy-Cache $upstream_cache_status;
        add_header                  X-ImageProxy-Debug $debugkey;
        expires                     24h;
        add_header                  Cache-Control "public";

        image_filter_sharpen        $sharpen;
        image_filter_jpeg_quality   $quality;
        image_filter_webp_quality   $quality;
        image_filter_output         $ofmt;
        image_filter                rotate $rotate;

    #image_filter watermark /path/to/watermark.png [ bottom-right (default) | top-left | top-right | bottom-left | center ];
        image_filter watermark /var/www/web/protected/media/logo.png center;
        image_filter                resize $width $height;
    }

    location /cmd/crop {
        internal;

        proxy_pass                  $clean_uri;
        include                     /usr/local/nginx/conf/conf.d/proxy-hide-headers.common;

        add_header                  X-ImageProxy-Cache $upstream_cache_status;
        add_header                  X-ImageProxy-Debug $debugkey;
        expires                     24h;
        add_header                  Cache-Control "public";

        image_filter_sharpen        $sharpen;
        image_filter_jpeg_quality   $quality;
        image_filter_webp_quality   $quality;
        image_filter_output         $ofmt;
        image_filter                rotate $rotate;

        image_filter watermark /var/www/web/protected/media/logo.png center;

        image_filter_crop_offset    $crop_offx $crop_offy;
        image_filter                crop $width $height;
    }
```

and I assume it gets the file cause if I change the path to a wrong one I see some errors of unable to serve the watermark image on the nginx error log.

**Comment by noogen** [comment]
Unforunately, you can't have multiple image_filter directive.  I'll have to go back to the drawing board and change the watermark to a different directive.

**Comment by noogen** [comment]
Ok, so the new directive look like this: https://github.com/niiknow/docker-nginx-image-proxy/blob/d803f2cbb5821cd5dc41b6a27d3fb09142c78264/files/etc/nginx/sites-enabled/server.conf#L242
```shell
# file must be png
image_filter_water_image /path/to/file/watermark.png;

# optional watermark positioning
image_filter_water_pos [ top-left | top-right | center | bottom-left | bottom-right (default)];
```

Here's the demo URL:  http://imageproxy.niiknow.org/rx/2010,water_1/https://octodex.github.com/images/codercat.jpg

And here is my demo config: https://gist.github.com/noogen/57bf47e4cd227f584b6ed8c4c9eb3eb6
