### ISSUE TITLE
Can i scale image like cloudinary

### ISSUE THREAD

**Issue by JJigar** [niiknow/docker-nginx-image-proxy#15]
Is there any provision to scale whole image,. which cloudinary does by using "c_scale"?

https://res.cloudinary.com/demo/image/upload/w_100,h_100,c_scale/turtles.jpg

**Comment by noogen** [comment]
Unfortunately, this library does not support scaling.  This mean no image enlarge, stretch, or shrunken based on both width and height combine.

It will only resize (shrink) an image if you provide either width or height.  The other width or height will shrink based on the original aspect ratio.

You can alternatively do your scaling with css.

**Comment by JJigar** [comment]
Thanks for the info noogen.
