### ISSUE TITLE
Trying to compile with your module in nginx 1.15.3 give errors

### ISSUE THREAD

**Issue by andreapernici** [niiknow/docker-nginx-image-proxy#16]
using these break compilation

https://github.com/niiknow/docker-nginx-image-proxy/blob/master/build/src/ngx_http_image_filter_module.c

**Comment by noogen** [comment]
What error are you getting?  I don't have a problem compiling on 1.15.3.   Remember you have to modify the nginx source at two location in two different files:

https://github.com/niiknow/docker-nginx-image-proxy/blob/master/build/src/ubuntu.sh#L18
https://github.com/niiknow/docker-nginx-image-proxy/blob/master/build/src/ubuntu.sh#L19
https://github.com/niiknow/docker-nginx-image-proxy/blob/master/Dockerfile#L25
https://github.com/niiknow/docker-nginx-image-proxy/blob/master/Dockerfile#L26

Add mainline between package and ubuntu:
```
packages/mainline/ubuntu/
```

**Comment by noogen** [comment]
I also checked all nginx release notes and the source here:  https://github.com/nginx/nginx/blob/master/src/http/modules/ngx_http_image_filter_module.c

There is no mention in release notes of any changes to image filter and the source has not change in ages (a year ago).  So I don't see why it would not build.

**Comment by andreapernici** [comment]
I'm using centos.

The issue I'm facing is that installing it in the standard way I get errors on webp stuff and output format.

When I restart nginx it fails cause of "unknown command".

Just to be clear this is my compilation:

```
[root@host nginx]# sbin/nginx -V
nginx version: nginx/1.15.3
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)
built with OpenSSL 1.1.0i  14 Aug 2018
TLS SNI support enabled
configure arguments: --user=nginx --group=nginx --with-http_ssl_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_stub_status_module --with-http_auth_request_module --with-threads --with-stream --with-stream_ssl_module --with-http_slice_module --with-mail --with-mail_ssl_module --with-file-aio --with-http_v2_module --with-stream_ssl_preread_module --with-openssl=../openssl-1.1.0i --add-module=../ngx_cache_purge --with-zlib=../zlib-1.2.11 --with-pcre=/usr/lib64/ --add-module=../ngx_brotli --with-pcre=../pcre-8.38 --with-http_image_filter_module --add-module=../ngx_devel_kit-0.3.1rc1 --add-module=../set-misc-nginx-module-0.32
```

then after errors in missing stuff I substituted the image filter module of nginx sources with https://github.com/niiknow/docker-nginx-image-proxy/blob/master/build/src/ngx_http_image_filter_module.c

but during the compilation it fails.

**Comment by noogen** [comment]
This image_filter module use libgd to output/create webp:  https://github.com/niiknow/docker-nginx-image-proxy/blob/master/build/src/ubuntu.sh#L24

Which libgd (gd-devel) version do you have installed?  libgd before 2.1.0 does not have webp support.  I'm not too familiar with compiling things on centos, but I read that most centos distribute gd-devel 2.0.x rpm, try: yum search gd-devel

Example, I see 2.0.35 listed for centos here: https://rpmfind.net/linux/rpm2html/search.php?query=gd-devel(x86-64)

**Comment by noogen** [comment]
You may want to try installing it from remi repo?  https://pkgs.org/download/gd-devel

I think it's something like:
```
yum remove gd-devel
yum --enablerepo=remi install gd-last-devel
```

**Comment by andreapernici** [comment]
Great. Looks like it now works
```
checking for GD library ... found
checking for GD WebP support ... found
```

but when I test the vhost configuration I see

`nginx: [emerg] unknown directive "image_filter_webp_quality" in /usr/local/nginx/conf/conf.d/www.it.conf:245`

and

```
nginx: [emerg] unknown directive "image_filter_output" in /usr/local/nginx/conf/conf.d/www.it.conf:246
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed
```

and the strange thing is that I also see this if I uncomment image_filter_interlace

`nginx: [emerg] unknown directive "image_filter_interlace" in /usr/local/nginx/conf/conf.d/www.it.conf:45`

**Comment by noogen** [comment]
image_filter_interlace is a built-in directive by the original nginx image_filter module.  If you get that error, it means you do not have the image_filter module.

Did you forget to load the image filter module?  Default nginx build config for most Linux distro is to have image filter as a dynamic module, example:  https://github.com/niiknow/dockers/blob/master/openresty/Dockerfile#L20

In this project docker, I configure it not dynamic:  https://github.com/niiknow/docker-nginx-image-proxy/blob/master/build/src/ubuntu.sh#L40

If it is a dynamic module, you must load the module in your nginx conf:  
```
load_module /path/to/nginx/modules/ngx_http_image_filter_module.so
```

**Comment by noogen** [comment]
Also, remember to replace the nginx image filter module before you do the build: https://github.com/niiknow/docker-nginx-image-proxy/blob/master/build/src/ubuntu.sh#L36

```
rm -f ${NGINX_BUILD_DIR}/nginx-${NGINX_VERSION}/src/http/modules/ngx_http_image_filter_module.c
curl -SL https://raw.githubusercontent.com/niiknow/docker-nginx-image-proxy/master/build/src/ngx_http_image_filter_module.c --output ${NGINX_BUILD_DIR}/nginx-${NGINX_VERSION}/src/http/modules/ngx_http_image_filter_module.c
```

**Comment by andreapernici** [comment]
It's very very strange cause the other directives work.

resize, crop, jpeg_quality etc etc...

Now I re-dowloaded the sources, substituted your file patch and recompiled and everything works.

I think something messed up with the source code. Thanks noogen. Will try also the watermark stuff now. Is the readme file updated with all the parameter examples?

**Comment by noogen** [comment]
That's why I usually run things as docker.  Too many variant to mess with different Linux distro and version.

It should be, try it.  I have not made any update to support shortcut/code watermark in the server.conf file.
