### ISSUE TITLE
Is there a way to use local path instead of URL?

### ISSUE THREAD

**Issue by andreapernici** [niiknow/docker-nginx-image-proxy#17]
I mean

can I transform 

image.xxx.it/rx/50/https://xxx.it/media/banners/1608/ciao.jpg

in 

image.xxx.it/rx/50/media/banners/1608/ciao.jpg

?

**Comment by noogen** [comment]
How about?  image.xxx.it/rx/50/image.xxx.it/media/banners/1608/ciao.jpg  or image.xxx.it/rx/50/localhost/media/banners/1608/ciao.jpg

You don't need to provide a protocol.  It's being done here:   https://github.com/niiknow/docker-nginx-image-proxy/blob/master/files/etc/nginx/sites-enabled/server.conf#L90 

Of course, you can always modify server.conf and make changes to be more flexible.

**Comment by andreapernici** [comment]
ok thanks. I also figured out how to avoid completely the URL.
