### ISSUE TITLE
Animated gif

### ISSUE THREAD

**Issue by andreapernici** [niiknow/docker-nginx-image-proxy#18]
Does the image filter module support animated GIF resize keeping it animated?

Made some test but resizing an animated Gif lead to a static Gif.

**Comment by noogen** [comment]
No it does not: https://github.com/niiknow/docker-nginx-image-proxy/blob/master/README.md#and-what-it-doesnt

See libgd comments here: https://github.com/libgd/libgd/issues/396

**Comment by andreapernici** [comment]
So we have to wait for the libgd team to make this happen ;)
