### ISSUE TITLE
Implementing stale while revalidate

### ISSUE THREAD

**Issue by andreapernici** [niiknow/docker-nginx-image-proxy#19]
I would suggest an enhancement for the image delivery. It makes sense a lot to setup the SWR nginx stuff for images.

```
        proxy_cache_use_stale updating error timeout http_500 http_502 http_503 http_504;
        proxy_cache_background_update on;
```

**Comment by noogen** [comment]
Added to default config, since it's a config change, I've rolled up into issue #21 update too.
