### ISSUE TITLE
i think that would you like to get me example about conf

### ISSUE THREAD

**Issue by l764191074** [niiknow/docker-nginx-image-proxy#22]
docs is to simlpe

**Comment by noogen** [comment]
The file is here:  https://github.com/niiknow/docker-nginx-image-proxy/blob/master/files/etc/nginx/sites-enabled/server.conf

The demo on the home page should be working now with the new v2, example: http://imageproxy.niiknow.org/rx/50/https://octodex.github.com/images/codercat.jpg
