### ISSUE TITLE
Often PNG resized files become bigger than the original.

### ISSUE THREAD

**Issue by andreapernici** [niiknow/docker-nginx-image-proxy#26]
I noticed that often PNG becomes bigger than the original.

Is there a fix for this?

**Comment by noogen** [comment]
Sorry, I've been on vacation.  Just got back last night.  Anyway, bigger how?  Bigger in size or in dimension?  Can you provide example?

Example below show that it actually reduce in size when resize to the same dimension:

before: https://www.blackjackapprenticeship.com/wp-content/uploads/2018/10/mini-blackjack-strategy-chart.png - 72.59KB

after: http://imageproxy.niiknow.org/rx/124/https://www.blackjackapprenticeship.com/wp-content/uploads/2018/10/mini-blackjack-strategy-chart.png - 18.51KB

Now if we're talking about dimension, what version are you using?  The latest version added - image_filter_scale_max with default value to 3 allowing for upsizing.  To prevent upscale, try setting this value to 1.

**Comment by noogen** [comment]
Also, if you're using an older version.  Maybe the issue is this one that I have previously resolved?  https://github.com/niiknow/docker-nginx-image-proxy/commit/a901c3e432114df5c2b4784a4966a671ad54b498

**Comment by andreapernici** [comment]
Already using the last but

- https://www.advancedseotool.it/storage/ast/css/img/dove-mob.png - 650kb
- https://image.searchon.it/rx/w_950/https://www.advancedseotool.it/storage/ast/css/img/dove-mob.png - 1mb

Pretty strange.

**Comment by noogen** [comment]
Apparently, resizing png can cause it to grow in size, see explanation here: https://stackoverflow.com/questions/14008524/why-smaller-png-image-takes-up-more-space-than-the-original-after-getting-resize

Alternatively, you can try forcing output to jpeg or webp if you want to compress it: 

https://image.searchon.it/rx/w_950,ofmt_jpeg/https://www.advancedseotool.it/storage/ast/css/img/dove-mob.png
https://image.searchon.it/rx/w_950,ofmt_webp/https://www.advancedseotool.it/storage/ast/css/img/dove-mob.png
