### ISSUE TITLE
415 unsupported media type on some https site

### ISSUE THREAD

**Issue by sageworm** [niiknow/docker-nginx-image-proxy#3]
HI, i did tried to make private image proxy with this awesome docker image but i found out that sometimes it doesnt work for (in my opinion) https sites/protocol and it throw 415 error code without redirect to origin

example:
http://imageproxy.niiknow.org/rx/x100/https://mir-s3-cdn-cf.behance.net/project_modules/1400/58dcf250511131.59246de683a1b.jpg

while the origin is obviously a perfect image in place 
https://mir-s3-cdn-cf.behance.net/project_modules/1400/58dcf250511131.59246de683a1b.jpg

I wonder what causing this and if there's improvements, thanks and great job!

**Comment by noogen** [comment]
Thanks for reporting.  You are right.  I get this error from the server:
 *1415 SSL_do_handshake() failed (SSL: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure) while SSL handshaking to upstream, 

I believe this is your issue:

https://stackoverflow.com/questions/25329941/nginx-caching-proxy-fails-with-ssl23-get-server-hellosslv3-alert-handshake-fail

I will test it out by updating my conf file and the docker image.

**Comment by noogen** [comment]
It should work now.  Simply add _proxy_ssl_server_name_ to your server conf:
```
proxy_ssl_server_name on;
```

**Comment by sageworm** [comment]
great man! thanks its working now
